-- ============================================================================
-- SCRIPT DE INICIALIZAÇÃO COMPLETO - CELD DISTRIBUIDORA
-- Banco de Dados: Supabase (Limpo, sem tabelas antigas de consórcio)
-- ============================================================================

-- 0. EXTENSÕES DO POSTGRES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. ESTRUTURA DE TABELAS

-- Organizações (Tenants)
CREATE TABLE IF NOT EXISTS public.organizations (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    domain text,
    mercadopago_access_token text,
    mercadopago_public_key text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Perfis de Usuários (Integrado com Supabase Auth)
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    mocha_user_id text UNIQUE,
    cpf text UNIQUE,
    role text DEFAULT 'affiliate'::text,
    is_active boolean DEFAULT true,
    sponsor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    company_name text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    email text,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    avatar_url text,
    referrer_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    registration_type text,
    status text DEFAULT 'active'::text,
    cnpj text,
    total_sales numeric DEFAULT 0.00,
    rank text DEFAULT 'Consultor'::text,
    leadership_bonus_total numeric DEFAULT 0.00,
    login text,
    balance numeric DEFAULT 0.00,
    total_earnings numeric DEFAULT 0.00,
    monthly_commission_total numeric DEFAULT 0.00,
    last_commission_reset timestamp with time zone,
    last_activation_at timestamp with time zone,
    whatsapp text,
    full_name text,
    city text,
    pix_key text,
    cep text,
    address text,
    street text,
    number text,
    complement text,
    neighborhood text,
    state text
);

-- Afiliados (Árvore e Rede MMN)
CREATE TABLE IF NOT EXISTS public.affiliates (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name text,
    cpf text,
    email text,
    whatsapp text,
    referral_code text,
    sponsor_id uuid REFERENCES public.affiliates(id) ON DELETE SET NULL,
    is_active boolean DEFAULT false,
    is_verified boolean DEFAULT false,
    last_access_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    position_slot integer,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    cnpj text,
    avatar_url text,
    cep text,
    address text,
    street text,
    number text,
    complement text,
    neighborhood text,
    city text,
    state text,
    active_until timestamp with time zone, -- Controle de Mensalidade 30 dias CELD
    CONSTRAINT affiliates_referral_code_org_key UNIQUE (organization_id, referral_code),
    CONSTRAINT affiliates_cpf_org_key UNIQUE (organization_id, cpf)
);

-- Configurações Financeiras de Carteira
CREATE TABLE IF NOT EXISTS public.user_settings (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    pix_key text,
    leg_preference text DEFAULT 'automatic'::text,
    total_earnings numeric DEFAULT 0.00,
    available_balance numeric DEFAULT 0.00,
    frozen_balance numeric DEFAULT 0.00,
    is_active_this_month boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    active_until timestamp with time zone -- Controle de Mensalidade 30 dias CELD
);

-- Categorias de Produtos
CREATE TABLE IF NOT EXISTS public.product_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    parent_id bigint REFERENCES public.product_categories(id) ON DELETE SET NULL,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    CONSTRAINT product_categories_name_org_key UNIQUE (organization_id, name)
);

-- Subcategorias de Produtos
CREATE TABLE IF NOT EXISTS public.product_subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category_id bigint REFERENCES public.product_categories(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now()
);

-- Produtos
CREATE TABLE IF NOT EXISTS public.products (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    description text,
    category_id bigint REFERENCES public.product_categories(id) ON DELETE SET NULL,
    price numeric NOT NULL,
    stock_quantity integer DEFAULT 0,
    image_url text,
    is_active boolean DEFAULT true,
    sales_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    weight numeric DEFAULT 0.00,
    length integer DEFAULT 0,
    width integer DEFAULT 0,
    height integer DEFAULT 0,
    origin_zip text,
    subcategory_id bigint REFERENCES public.product_subcategories(id) ON DELETE SET NULL,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    variations jsonb DEFAULT '{}'::jsonb,
    is_leadership_item boolean DEFAULT false
);

-- Pedidos (Compras de Planos e Cesta Básica)
CREATE TABLE IF NOT EXISTS public.orders (
    id text PRIMARY KEY,
    customer_email text,
    customer_phone text,
    shipping_address text,
    total_amount numeric NOT NULL,
    status text DEFAULT 'Pendente'::text,
    payment_method text,
    referral_code text,
    tracking_code text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    payment_id text,
    payment_preference_id text,
    payment_status_detail text,
    customer_cpf text,
    shipping_cost numeric DEFAULT 0.00,
    shipping_method text,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    leadership_bonus_amount numeric DEFAULT 0.00,
    affiliate_id uuid,
    commission_amount numeric DEFAULT 0.00,
    email text,
    nome text,
    whatsapp text,
    items jsonb DEFAULT '[]'::jsonb,
    referrer_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
    payment_status text,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    pix_qr_code text,
    pix_qr_code_base64 text,
    pix_copy_paste text,
    customer_name text
);

-- Itens do Pedido
CREATE TABLE IF NOT EXISTS public.order_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id text REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
    product_name text NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE
);

-- Histórico de Comissões Pagas
CREATE TABLE IF NOT EXISTS public.commissions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    order_id text REFERENCES public.orders(id) ON DELETE CASCADE,
    amount numeric NOT NULL,
    level integer NOT NULL,
    commission_type text,
    description text,
    created_at timestamp with time zone DEFAULT now()
);

-- Configurações Gerais de Comissões (Porcentagens Multinível)
CREATE TABLE IF NOT EXISTS public.commission_configs (
    key text NOT NULL,
    type text DEFAULT 'percent'::text,
    active_generations integer DEFAULT 10,
    levels jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    PRIMARY KEY (key, organization_id)
);

-- Solicitações de Saques
CREATE TABLE IF NOT EXISTS public.withdrawals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    amount_requested numeric NOT NULL,
    fee_amount numeric DEFAULT 0.00,
    net_amount numeric NOT NULL,
    status text DEFAULT 'pending'::text,
    pix_key text NOT NULL,
    processed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE
);

-- Materiais de Apoio / Marketing
CREATE TABLE IF NOT EXISTS public.marketing_materials (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    title text NOT NULL,
    description text,
    type text NOT NULL, -- video, pdf, image, slide, etc.
    thumbnail_url text,
    file_url text,
    content text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE
);

-- Logs do Sistema
CREATE TABLE IF NOT EXISTS public.debug_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    message text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- Logs de Segurança
CREATE TABLE IF NOT EXISTS public.security_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email text,
    ip_address text,
    location text,
    device_info text,
    event_type text NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


-- ============================================================================
-- 2. FUNÇÕES E ROTINAS DO SISTEMA
-- ============================================================================

-- A. Função Auxiliar para verificar se o usuário é administrador
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN (
    SELECT role = 'admin'
    FROM public.user_profiles
    WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- B. Atualização Automática do campo updated_at
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_organizations_updated_at BEFORE UPDATE ON public.organizations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_user_profiles_updated_at BEFORE UPDATE ON public.user_profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_affiliates_updated_at BEFORE UPDATE ON public.affiliates FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_user_settings_updated_at BEFORE UPDATE ON public.user_settings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_marketing_materials_updated_at BEFORE UPDATE ON public.marketing_materials FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- C. Trigger: Configurar Dinamicamente a Organização (Tenant) no Cadastro
CREATE OR REPLACE FUNCTION public.handle_auth_user_app_metadata()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE 
    v_org_id uuid;
BEGIN
  -- Tenta resgatar organization_id do cadastro do usuário
  v_org_id := NULLIF(new.raw_user_meta_data ->> 'organization_id', '')::uuid;
  
  -- Se estiver vazio, joga no ID padrão da CELD Distribuidora
  IF v_org_id IS NULL THEN
     SELECT id INTO v_org_id FROM public.organizations WHERE name = 'CELD Distribuidora' LIMIT 1;
  END IF;

  -- Insere no app_metadata para validação segura via JWT nas políticas RLS
  new.raw_app_meta_data := coalesce(new.raw_app_meta_data, '{}'::jsonb) || jsonb_build_object('organization_id', v_org_id);
  
  RETURN new;
END;
$function$;

DROP TRIGGER IF EXISTS on_auth_user_app_metadata ON auth.users;
CREATE TRIGGER on_auth_user_app_metadata
  BEFORE INSERT OR UPDATE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_app_metadata();


-- D. Trigger: Sincronização e Cadastro Automático do Afiliado (Após Inserção no Auth.Users)
CREATE OR REPLACE FUNCTION public.handle_new_affiliate_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
 AS $function$
 DECLARE
   v_full_name text;
   v_sponsor_affiliate_id uuid;
   v_sponsor_user_id uuid;
   v_org_id uuid;
   v_sponsor_code text;
   v_login text;
   v_temp_login text;
   v_exists boolean;
   v_counter integer := 0;
 BEGIN
   -- 1. Determinar Organização de forma DINÂMICA
   v_org_id := NULLIF(new.raw_user_meta_data ->> 'organization_id', '')::uuid;
   
   IF v_org_id IS NULL AND (new.raw_user_meta_data ->> 'organization_name') IS NOT NULL THEN
      SELECT id INTO v_org_id FROM public.organizations 
      WHERE LOWER(name) = LOWER(new.raw_user_meta_data ->> 'organization_name') 
      LIMIT 1;
   END IF;

   -- Fallback de segurança para CELD Distribuidora
   IF v_org_id IS NULL THEN
      SELECT id INTO v_org_id FROM public.organizations WHERE name = 'CELD Distribuidora' LIMIT 1;
   END IF;

   -- Se ainda não existir a organização no banco, lança erro
   IF v_org_id IS NULL THEN
      RAISE EXCEPTION 'Multi-tenant Error: Nenhuma organização padrão encontrada.';
   END IF;

   -- 2. Determinar Dados Básicos do Usuário
   v_login := LOWER(TRIM(COALESCE(new.raw_user_meta_data ->> 'login', split_part(new.email, '@', 1))));
   v_full_name := TRIM(CONCAT_WS(' ', new.raw_user_meta_data ->> 'nome', new.raw_user_meta_data ->> 'sobrenome'));
   IF v_full_name = '' OR v_full_name IS NULL THEN 
     v_full_name := COALESCE(new.raw_user_meta_data ->> 'nome', v_login); 
   END IF;

   -- 3. Evitar colisão de código de indicação (referral_code)
   v_temp_login := v_login;
   LOOP
     SELECT EXISTS (
       SELECT 1 FROM public.affiliates 
       WHERE LOWER(referral_code) = v_temp_login 
       AND organization_id = v_org_id
     ) INTO v_exists;
     
     EXIT WHEN NOT v_exists OR v_counter > 10;
     
     v_counter := v_counter + 1;
     v_temp_login := v_login || substr(md5(random()::text), 1, 4);
   END LOOP;
   v_login := v_temp_login;

   -- 4. Resolver Padrinho (Sponsor) dentro do mesmo inquilino
   v_sponsor_code := NULLIF(new.raw_user_meta_data ->> 'sponsor_code', '');
   
   IF v_sponsor_code IS NOT NULL THEN
     SELECT id, user_id INTO v_sponsor_affiliate_id, v_sponsor_user_id
     FROM public.affiliates 
     WHERE LOWER(referral_code) = LOWER(v_sponsor_code)
     AND organization_id = v_org_id
     LIMIT 1;
   END IF;

   -- Fallback para o afiliado raiz da CELD se nenhum patrocinador for informado
   IF v_sponsor_user_id IS NULL THEN
     SELECT id, user_id INTO v_sponsor_affiliate_id, v_sponsor_user_id
     FROM public.affiliates
     WHERE organization_id = v_org_id
     ORDER BY created_at ASC
     LIMIT 1;
   END IF;

   -- 5. Inserir na tabela user_profiles
   INSERT INTO public.user_profiles (
     id, email, role, full_name, login, 
     organization_id, sponsor_id, referrer_id,
     status, rank, created_at, updated_at
   )
   VALUES (
     new.id, 
     new.email, 
     COALESCE(new.raw_user_meta_data ->> 'role', 'affiliate'),
     v_full_name,
     v_login,
     v_org_id,
     v_sponsor_user_id,
     v_sponsor_user_id,
     'active',
     'Consultor',
     new.created_at, 
     new.created_at
   )
   ON CONFLICT (id) DO UPDATE SET
     full_name = EXCLUDED.full_name,
     login = EXCLUDED.login,
     organization_id = EXCLUDED.organization_id,
     sponsor_id = EXCLUDED.sponsor_id;

   -- 6. Inserir na tabela affiliates
   INSERT INTO public.affiliates (
     user_id, email, full_name, referral_code, 
     organization_id, sponsor_id, 
     is_active, created_at, updated_at
   )
   VALUES (
     new.id,
     new.email,
     v_full_name,
     v_login,
     v_org_id,
     v_sponsor_affiliate_id,
     false, -- Começa inativo até comprar a primeira cesta básica
     new.created_at,
     new.created_at
   )
   ON CONFLICT (user_id) DO UPDATE SET
     full_name = EXCLUDED.full_name,
     referral_code = EXCLUDED.referral_code,
     sponsor_id = EXCLUDED.sponsor_id;

   -- 7. Inserir na tabela user_settings
   INSERT INTO public.user_settings (user_id, organization_id, created_at, updated_at)
   VALUES (new.id, v_org_id, new.created_at, new.created_at)
   ON CONFLICT (user_id) DO NOTHING;
   
   RETURN new;
 END;
 $function$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_affiliate_user();


-- E. Trigger: Ativação Automática de 30 Dias (CELD Activation)
CREATE OR REPLACE FUNCTION public.handle_celd_activation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_is_celd_plan boolean := false;
    v_current_active_until timestamp with time zone;
    v_new_active_until timestamp with time zone;
BEGIN
    -- Só processa se o status mudar para 'Pago'
    IF (OLD.status <> 'Pago' AND NEW.status = 'Pago') THEN
        
        -- Verifica se o pedido contém o item de Plano Único (R$ 300,00 ou nome com Cesta)
        SELECT EXISTS (
            SELECT 1 FROM public.order_items oi
            JOIN public.products p ON oi.product_id = p.id
            LEFT JOIN public.product_categories pc ON p.category_id = pc.id
            WHERE oi.order_id = NEW.id
            AND (oi.unit_price = 300.00 OR p.price = 300.00 OR p.name ILIKE '%Cesta%' OR pc.name ILIKE '%Cesta%')
        ) INTO v_is_celd_plan;

        -- Se for a ativação da Cesta Básica CELD e o usuário estiver definido
        IF v_is_celd_plan AND NEW.user_id IS NOT NULL THEN
            -- Pega data de vencimento atual
            SELECT active_until INTO v_current_active_until 
            FROM public.affiliates 
            WHERE user_id = NEW.user_id 
            AND organization_id = NEW.organization_id
            LIMIT 1;

            -- Se o usuário já estiver ativo (data no futuro), adiciona mais 30 dias.
            -- Se estiver vencido ou nulo, inicia os 30 dias a partir da data de hoje.
            IF v_current_active_until IS NOT NULL AND v_current_active_until >= NOW() THEN
                v_new_active_until := v_current_active_until + INTERVAL '30 days';
            ELSE
                v_new_active_until := NOW() + INTERVAL '30 days';
            END IF;

            -- Grava o novo prazo em affiliates
            UPDATE public.affiliates 
            SET 
                active_until = v_new_active_until,
                is_active = true,
                updated_at = NOW()
            WHERE user_id = NEW.user_id 
            AND organization_id = NEW.organization_id;

            -- Grava o novo prazo em user_settings
            UPDATE public.user_settings 
            SET 
                active_until = v_new_active_until,
                is_active_this_month = true,
                updated_at = NOW()
            WHERE user_id = NEW.user_id 
            AND organization_id = NEW.organization_id;

            -- Grava log de auditoria
            INSERT INTO public.debug_logs (operation, message, metadata)
            VALUES (
                'CELD_ACTIVATION',
                'Afiliado ' || NEW.user_id || ' ativado até ' || v_new_active_until,
                jsonb_build_object('order_id', NEW.id, 'user_id', NEW.user_id, 'previous_active_until', v_current_active_until, 'new_active_until', v_new_active_until)
            );
            
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_handle_celd_activation ON public.orders;
CREATE TRIGGER trigger_handle_celd_activation
    AFTER UPDATE ON public.orders
    FOR EACH ROW
    WHEN (OLD.status <> 'Pago' AND NEW.status = 'Pago')
    EXECUTE FUNCTION public.handle_celd_activation();


-- F. Trigger: Distribuição de Comissões MMN com Compressão Dinâmica (Verifica active_until)
CREATE OR REPLACE FUNCTION public.distribute_commissions()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_affiliate RECORD;
    v_current_sponsor_id uuid;
    v_sponsor_rec RECORD;
    v_config RECORD;
    v_commission_amount numeric;
    v_gen_count integer := 0;
    v_active_gens integer;
    v_target_user_id uuid;
BEGIN
    -- Só processa se o status mudar para 'Pago'
    IF (OLD.status IS NULL OR OLD.status != 'Pago') AND NEW.status = 'Pago' THEN
        
        -- Evita pagamento em duplicidade
        IF EXISTS (SELECT 1 FROM public.commissions WHERE order_id = NEW.id) THEN
            RETURN NEW;
        END IF;

        -- Busca Configuração Unilevel Geral da Organização
        SELECT * INTO v_config 
        FROM public.commission_configs 
        WHERE key = 'geral' 
        AND organization_id = NEW.organization_id;
        
        IF v_config IS NULL THEN
            RETURN NEW;
        END IF;

        v_active_gens := v_config.active_generations;

        -- 1. Identificar o Afiliado que indicou a venda (Nível de indicação inicial)
        -- Prioridade 1: Código de indicação no pedido
        IF NEW.referral_code IS NOT NULL AND NEW.referral_code != '' THEN
            SELECT * INTO v_affiliate FROM public.affiliates 
            WHERE LOWER(referral_code) = LOWER(NEW.referral_code) 
            AND organization_id = NEW.organization_id
            LIMIT 1;
        END IF;

        -- Prioridade 2: Padrinho direto cadastrado no perfil do comprador
        IF v_affiliate IS NULL AND NEW.user_id IS NOT NULL THEN
            SELECT a.* INTO v_affiliate 
            FROM public.affiliates a
            JOIN public.user_profiles p ON p.sponsor_id = a.user_id
            WHERE p.id = NEW.user_id 
            AND a.organization_id = NEW.organization_id
            LIMIT 1;
        END IF;

        -- Se não houver padrinho ou afiliado, a comissão não sobe
        IF v_affiliate IS NULL THEN
            RETURN NEW;
        END IF;

        -- Inicia subida na rede a partir do patrocinador direto
        v_current_sponsor_id := v_affiliate.id;

        -- 2. Loop de Distribuição das Gerações (Unilevel 10 Níveis com Compressão Dinâmica)
        WHILE v_gen_count < v_active_gens AND v_current_sponsor_id IS NOT NULL LOOP
            -- Pega informações do patrocinador da vez
            SELECT user_id, sponsor_id, active_until, is_active 
            INTO v_sponsor_rec 
            FROM public.affiliates 
            WHERE id = v_current_sponsor_id 
            AND organization_id = NEW.organization_id;
            
            IF v_sponsor_rec IS NULL THEN
                EXIT;
            END IF;

            -- COMPRESSÃO DINÂMICA CELD:
            -- Só paga a comissão da geração atual se o patrocinador estiver com mensalidade ativa (active_until >= hoje)
            IF v_sponsor_rec.active_until IS NOT NULL AND v_sponsor_rec.active_until >= NOW() THEN
                -- Incrementa o nível de pagamento a ser distribuído
                v_gen_count := v_gen_count + 1;
                
                -- Carrega percentual do nível
                SELECT (lvl->>'value')::numeric INTO v_commission_amount
                FROM jsonb_array_elements(v_config.levels) AS lvl
                WHERE (lvl->>'level')::integer = v_gen_count;

                IF v_commission_amount IS NOT NULL AND v_commission_amount > 0 THEN
                    -- Se a comissão for porcentagem, calcula em cima do total da compra
                    IF v_config.type = 'percent' THEN
                        v_commission_amount := NEW.total_amount * (v_commission_amount / 100);
                    END IF;

                    -- Credita o valor na carteira do patrocinador
                    UPDATE public.user_settings 
                    SET 
                        total_earnings = total_earnings + v_commission_amount,
                        available_balance = available_balance + v_commission_amount,
                        updated_at = now()
                    WHERE user_id = v_sponsor_rec.user_id;

                    -- Insere registro histórico na tabela de comissões
                    INSERT INTO public.commissions (
                        organization_id,
                        user_id,
                        order_id,
                        amount,
                        level,
                        commission_type,
                        description
                    ) VALUES (
                        NEW.organization_id,
                        v_sponsor_rec.user_id,
                        NEW.id,
                        v_commission_amount,
                        v_gen_count,
                        v_config.type,
                        'Comissão Unilevel G' || v_gen_count || ' - Indicação no Pedido ' || NEW.id
                    );
                END IF;
            ELSE
                -- Patrocinador está INATIVO/INADIMPLENTE!
                -- A comissão de Geração não é creditada a ele.
                -- Graças à compressão dinâmica, pulamos ele e continuamos a busca na linha ascendente
                -- para pagar esta geração a um padrinho ativo acima, garantindo o repasse correto do plano.
                INSERT INTO public.debug_logs (operation, message, metadata)
                VALUES (
                    'COMMISSION_COMPRESSION_SKIP',
                    'Sponsor ' || v_sponsor_rec.user_id || ' inativo. Comissão Geração pulada/comprimida.',
                    jsonb_build_object('order_id', NEW.id, 'inactive_user_id', v_sponsor_rec.user_id, 'active_until', v_sponsor_rec.active_until)
                );
            END IF;

            -- Sobe para o patrocinador do patrocinador atual
            v_current_sponsor_id := v_sponsor_rec.sponsor_id;
            
            -- Salvaguarda contra loops infinitos
            IF v_gen_count > 50 THEN EXIT; END IF;
        END LOOP;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_distribute_commissions ON public.orders;
CREATE TRIGGER trigger_distribute_commissions
    AFTER UPDATE ON public.orders
    FOR EACH ROW
    WHEN (OLD.status <> 'Pago' AND NEW.status = 'Pago')
    EXECUTE FUNCTION public.distribute_commissions();


-- ============================================================================
-- 3. POLÍTICAS DE SEGURANÇA (ROW LEVEL SECURITY - RLS)
-- ============================================================================

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_subcategories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commission_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.debug_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_logs ENABLE ROW LEVEL SECURITY;

-- Limpar quaisquer políticas legadas para recriar de forma limpa
DO $$ 
DECLARE 
    r RECORD;
BEGIN
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') 
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
    END LOOP;
END $$;

-- A. Políticas para: public.organizations
CREATE POLICY "Leitura_Publica_Organizations" ON public.organizations FOR SELECT USING (true);
CREATE POLICY "Admin_Full_Organizations" ON public.organizations FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- B. Políticas para: public.user_profiles
CREATE POLICY "Leitura_Profiles_Tenant" ON public.user_profiles FOR SELECT TO authenticated USING (organization_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::uuid OR public.is_admin());
CREATE POLICY "Atualizacao_Proprio_Profile" ON public.user_profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY "Admin_Full_Profiles" ON public.user_profiles FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- C. Políticas para: public.affiliates
CREATE POLICY "Leitura_Affiliates_Tenant" ON public.affiliates FOR SELECT TO authenticated USING (organization_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::uuid OR public.is_admin());
CREATE POLICY "Atualizacao_Proprio_Affiliate" ON public.affiliates FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Insert_Publico_Affiliate" ON public.affiliates FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin_Full_Affiliates" ON public.affiliates FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- D. Políticas para: public.user_settings
CREATE POLICY "Leitura_Settings_Tenant" ON public.user_settings FOR SELECT TO authenticated USING (organization_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::uuid OR public.is_admin());
CREATE POLICY "Atualizacao_Proprio_Settings" ON public.user_settings FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Admin_Full_Settings" ON public.user_settings FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- E. Políticas para: public.product_categories
CREATE POLICY "Leitura_Publica_Categories" ON public.product_categories FOR SELECT USING (true);
CREATE POLICY "Admin_Full_Categories" ON public.product_categories FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- F. Políticas para: public.product_subcategories
CREATE POLICY "Leitura_Publica_Subcategories" ON public.product_subcategories FOR SELECT USING (true);
CREATE POLICY "Admin_Full_Subcategories" ON public.product_subcategories FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- G. Políticas para: public.products
CREATE POLICY "Leitura_Publica_Products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admin_Full_Products" ON public.products FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- H. Políticas para: public.orders
CREATE POLICY "Leitura_Propria_Orders" ON public.orders FOR SELECT TO authenticated USING (user_id = auth.uid() OR customer_email = auth.jwt()->>'email');
CREATE POLICY "Leitura_Orders_Tenant" ON public.orders FOR SELECT TO authenticated USING (organization_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::uuid OR public.is_admin());
CREATE POLICY "Insert_Publico_Orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin_Full_Orders" ON public.orders FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- I. Políticas para: public.order_items
CREATE POLICY "Leitura_OrderItems_Tenant" ON public.order_items FOR SELECT TO authenticated USING (organization_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::uuid OR public.is_admin());
CREATE POLICY "Insert_Publico_OrderItems" ON public.order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin_Full_OrderItems" ON public.order_items FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- J. Políticas para: public.commissions
CREATE POLICY "Leitura_Propria_Commissions" ON public.commissions FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin());
CREATE POLICY "Admin_Full_Commissions" ON public.commissions FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- K. Políticas para: public.commission_configs
CREATE POLICY "Leitura_Config_Tenant" ON public.commission_configs FOR SELECT TO authenticated USING (organization_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::uuid OR public.is_admin());
CREATE POLICY "Admin_Full_Config" ON public.commission_configs FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- L. Políticas para: public.withdrawals
CREATE POLICY "Leitura_Propria_Withdrawals" ON public.withdrawals FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin());
CREATE POLICY "Inserir_Proprio_Saque" ON public.withdrawals FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "Admin_Full_Withdrawals" ON public.withdrawals FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- M. Políticas para: public.marketing_materials
CREATE POLICY "Leitura_Materials_Tenant" ON public.marketing_materials FOR SELECT TO authenticated USING (organization_id = (auth.jwt() -> 'app_metadata' ->> 'organization_id')::uuid OR public.is_admin());
CREATE POLICY "Admin_Full_Materials" ON public.marketing_materials FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- N. Políticas para: public.debug_logs
CREATE POLICY "Admin_Full_Debug_Logs" ON public.debug_logs FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- O. Políticas para: public.security_logs
CREATE POLICY "Admin_Full_Security_Logs" ON public.security_logs FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());


-- ============================================================================
-- 4. CARGA INICIAL DE DADOS (SEED DADOS DA CELD DISTRIBUIDORA)
-- ============================================================================

-- A. Inserir Organização Principal CELD Distribuidora
INSERT INTO public.organizations (id, name, domain) 
VALUES ('c01d919a-ce1d-4de5-b81d-c01d919ad151', 'CELD Distribuidora', 'celddistribuidora.com.br')
ON CONFLICT (id) DO NOTHING;

-- B. Inserir Configurações de Comissionamento MMN Unilevel (G1=10%, G2=5%, G3=4%, G4-G9=3%, G10=3.05%)
INSERT INTO public.commission_configs (key, type, active_generations, levels, organization_id)
VALUES (
  'geral',
  'percent',
  10,
  '[
    {"level": 1, "value": 10.0},
    {"level": 2, "value": 5.0},
    {"level": 3, "value": 4.0},
    {"level": 4, "value": 3.0},
    {"level": 5, "value": 3.0},
    {"level": 6, "value": 3.0},
    {"level": 7, "value": 3.0},
    {"level": 8, "value": 3.0},
    {"level": 9, "value": 3.0},
    {"level": 10, "value": 3.05}
  ]'::jsonb,
  'c01d919a-ce1d-4de5-b81d-c01d919ad151'
)
ON CONFLICT (key, organization_id) DO UPDATE SET
  levels = EXCLUDED.levels,
  active_generations = EXCLUDED.active_generations;

-- C. Inserir Categoria Padrão 'Alimentos'
INSERT INTO public.product_categories (id, name, organization_id) 
VALUES (1, 'Alimentos', 'c01d919a-ce1d-4de5-b81d-c01d919ad151')
ON CONFLICT (id) DO NOTHING;

-- D. Inserir Produto Plano Único (Cesta Básica CELD - R$ 300,00) que ativa a conta
INSERT INTO public.products (id, name, description, category_id, price, stock_quantity, image_url, is_active, organization_id, is_leadership_item)
VALUES (
  'd01d919a-ce1d-4de5-b81d-c01d919ad151',
  'Cesta Básica CELD (Plano Único)',
  'Cesta básica de alimentos essenciais. A compra mensal deste produto garante a sua ativação de 30 dias na rede MMN e o recebimento da sua cesta.',
  1,
  300.00,
  9999,
  'https://yyoahysmkvjvpdlciaoy.supabase.co/storage/v1/object/public/products/cesta-basica.png',
  true,
  'c01d919a-ce1d-4de5-b81d-c01d919ad151',
  false
)
ON CONFLICT (id) DO NOTHING;

-- E. Conceder permissões para os papéis de acesso do Supabase
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;


-- ============================================================================
-- 5. CRIAÇÃO DO USUÁRIO ADMINISTRADOR PADRÃO (CELD)
-- ============================================================================
DO $$
DECLARE
    v_user_id uuid := gen_random_uuid();
    v_org_id uuid := 'c01d919a-ce1d-4de5-b81d-c01d919ad151';
    v_email text := 'admin@celddistribuidora.com.br';
    v_password text := 'admin123';
    v_exists boolean;
BEGIN
    -- Verifica se o usuário já existe no auth.users
    SELECT EXISTS (SELECT 1 FROM auth.users WHERE email = v_email) INTO v_exists;

    IF NOT v_exists THEN
        -- 1. Inserir no auth.users do Supabase Auth (Gera a senha criptografada em bcrypt)
        INSERT INTO auth.users (
            instance_id,
            id,
            aud,
            role,
            email,
            encrypted_password,
            email_confirmed_at,
            raw_app_meta_data,
            raw_user_meta_data,
            created_at,
            updated_at,
            confirmation_token,
            email_change,
            email_change_token_new,
            recovery_token,
            is_super_admin
        ) VALUES (
            '00000000-0000-0000-0000-000000000000',
            v_user_id,
            'authenticated',
            'authenticated',
            v_email,
            crypt(v_password, gen_salt('bf', 10)),
            now(),
            jsonb_build_object('provider', 'email', 'providers', array['email'], 'organization_id', v_org_id),
            jsonb_build_object('nome', 'Administrador', 'sobrenome', 'CELD', 'login', 'admin', 'role', 'admin', 'organization_id', v_org_id),
            now(),
            now(),
            '',
            '',
            '',
            '',
            false
        );

        -- 2. Inserir no auth.identities (Necessário para o login por email/senha no Supabase Auth)
        INSERT INTO auth.identities (
            id,
            provider_id,
            user_id,
            identity_data,
            provider,
            last_sign_in_at,
            created_at,
            updated_at
        ) VALUES (
            gen_random_uuid(),
            v_user_id::text,
            v_user_id,
            jsonb_build_object('sub', v_user_id::text, 'email', v_email),
            'email',
            now(),
            now(),
            now()
        );

        -- 3. Atualiza o cadastro inserido na public.user_profiles pelo trigger para garantir o papel de 'admin'
        UPDATE public.user_profiles 
        SET role = 'admin' 
        WHERE id = v_user_id;

        RAISE NOTICE 'Usuário administrador % criado com sucesso!', v_email;
    ELSE
        RAISE NOTICE 'Usuário administrador % já existe.', v_email;
    END IF;
END $$;


-- ============================================================================
-- 6. CONFIGURAÇÃO DOS STORAGES (BUCKETS) E POLÍTICAS DE ACESSO
-- ============================================================================

-- A. Criação dos Buckets (caso não existam)
INSERT INTO storage.buckets (id, name, public) VALUES 
('avatars', 'avatars', true),
('product-images', 'product-images', true),
('marketing-materials', 'marketing-materials', true)
ON CONFLICT (id) DO NOTHING;

-- B. Limpar políticas de storage legadas para evitar conflitos
DROP POLICY IF EXISTS "Avatar public access" ON storage.objects;
DROP POLICY IF EXISTS "Avatar upload access" ON storage.objects;
DROP POLICY IF EXISTS "Avatar update access" ON storage.objects;
DROP POLICY IF EXISTS "Avatar delete access" ON storage.objects;

DROP POLICY IF EXISTS "Product images public access" ON storage.objects;
DROP POLICY IF EXISTS "Product images admin access" ON storage.objects;

DROP POLICY IF EXISTS "Marketing materials public access" ON storage.objects;
DROP POLICY IF EXISTS "Marketing materials admin access" ON storage.objects;

-- C. Políticas RLS para o bucket 'avatars'
-- 1. Leitura pública para fotos de perfil
CREATE POLICY "Avatar public access" ON storage.objects
  FOR SELECT USING (bucket_id = 'avatars');

-- 2. Permite que usuários autenticados enviem sua própria foto
CREATE POLICY "Avatar upload access" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'avatars' 
    AND auth.role() = 'authenticated' 
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- 3. Permite que usuários atualizem sua própria foto
CREATE POLICY "Avatar update access" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'avatars' 
    AND auth.role() = 'authenticated' 
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- 4. Permite que usuários excluam sua própria foto
CREATE POLICY "Avatar delete access" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'avatars' 
    AND auth.role() = 'authenticated' 
    AND (storage.foldername(name))[1] = auth.uid()::text
  );


-- D. Políticas RLS para o bucket 'product-images'
-- 1. Leitura pública para imagens dos produtos do catálogo
CREATE POLICY "Product images public access" ON storage.objects
  FOR SELECT USING (bucket_id = 'product-images');

-- 2. Acesso total para administradores
CREATE POLICY "Product images admin access" ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'product-images' AND public.is_admin())
  WITH CHECK (bucket_id = 'product-images' AND public.is_admin());


-- E. Políticas RLS para o bucket 'marketing-materials'
-- 1. Leitura pública/afiliados para materiais de marketing
CREATE POLICY "Marketing materials public access" ON storage.objects
  FOR SELECT USING (bucket_id = 'marketing-materials');

-- 2. Acesso total para administradores
CREATE POLICY "Marketing materials admin access" ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'marketing-materials' AND public.is_admin())
  WITH CHECK (bucket_id = 'marketing-materials' AND public.is_admin());


